#!/usr/bin/env python3
"""Generate CHANGELOG.md from the conventional prefixes already used in
commit subjects (`core:`, `app:`, `docs:`, `ci:`, `skills:`, …), grouped
per release tag (`harbor-v*`) with an Unreleased section on top.

  python3 tools/generate_changelog.py --write

Multi-prefix subjects (`core+app:`) are listed under each named area, and
a scope in parentheses (`fix(native):`, `test(app):`, `core(ffi):`) is
read as its area — before this, those landed under "Other" with the
prefix still in the entry text, which is what the release page showed.
A subject with no recognised prefix lands under "Other" unchanged.
"""
import argparse
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
AREAS = {
    "core": "Core", "ffi": "FFI", "app": "App", "ui": "UI", "skills": "Skills",
    "inference": "Inference", "contracts": "Contracts", "docs": "Docs", "ci": "CI",
    "schemas": "Contracts", "release": "Release", "tools": "Tools",
    "android": "App", "ios": "App", "native": "FFI", "test": "Tests",
    "chore": "Chore",
}
# `area:`, `area+area:` and `kind(area):` — the three shapes the log uses.
PREFIX = re.compile(r"^([a-z+]+)(?:\(([a-z+]+)\))?:\s*(.+)$")


def git(*args):
    return subprocess.check_output(["git", *args], cwd=ROOT, text=True).rstrip("\n")


def tags():
    out = git("tag", "--list", "harbor-v*", "--sort=-creatordate")
    return [t for t in out.split("\n") if t]


def commits(rev_range):
    out = git("log", "--no-merges", "--format=%H%x1f%s", rev_range)
    for line in out.split("\n"):
        if not line:
            continue
        sha, subject = line.split("\x1f", 1)
        yield sha[:10], subject


def section(title, rev_range):
    groups = {}
    for sha, subject in commits(rev_range):
        m = PREFIX.match(subject)
        if m:
            kind, scope, text = m.group(1), m.group(2), m.group(3)
            # A scope names the area more precisely than the kind does:
            # `fix(native)` is an FFI change, not a "fix" category.
            named = scope if scope else kind
            areas = named.split("+")
            # A kind with a scope neither of which is a known area (say
            # `chore(deps)`) still beats dropping the subject into Other
            # with its prefix attached.
            if not any(a in AREAS for a in areas) and kind in AREAS:
                areas = [kind]
        else:
            areas, text = ["other"], subject
        for a in areas:
            groups.setdefault(AREAS.get(a, "Other"), []).append(f"- {text} (`{sha}`)")
    if not groups:
        return f"## {title}\n\n_No changes._\n"
    body = [f"## {title}\n"]
    for area in sorted(groups, key=lambda k: (k == "Other", k)):
        body.append(f"### {area}\n")
        body.extend(groups[area])
        body.append("")
    return "\n".join(body) + "\n"


def render():
    parts = ["# Changelog\n",
             "Generated by `tools/generate_changelog.py` from commit subjects; "
             "one section per `harbor-v*` tag, newest first.\n"]
    ts = tags()
    head = "HEAD"
    if ts:
        parts.append(section("Unreleased", f"{ts[0]}..HEAD"))
        for i, t in enumerate(ts):
            older = ts[i + 1] if i + 1 < len(ts) else None
            rng = f"{older}..{t}" if older else t
            parts.append(section(t, rng))
    else:
        parts.append(section("Unreleased", head))
    return "\n".join(parts)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()
    text = render()
    if args.write:
        (ROOT / "CHANGELOG.md").write_text(text)
        print(f"wrote CHANGELOG.md ({len(text.splitlines())} lines)")
    else:
        print(text)


if __name__ == "__main__":
    main()
